### PR TITLE
Commit after class

### PR DESCRIPTION
**Pull request by lcampbe79**

### CODE REVIEW

**Comment by lcampbe79** [comment]
I have pretty good notes I think but still unsure how to implement. Some code has been written but sounds like I still don't understand the project overall and don't know how to form the right questions.

**Comment by lcampbe79** [comment]
After putting the code back to a stable version (1864f61), I am able to print 8 by using sys.argv. Realize now that my PRN and HLT functions are not being used or traceable in the trace function. Either way it is progress.

**Comment by lcampbe79** [comment]
(d320ef5) Was getting an "Unknown Instruction" due to the fact that in the trace function uses self.pc and not a temp variable I had (PC).

**Comment by lcampbe79** [comment]
(4b41e27) After working in a zoom, realized that moving the instructions to an object would be better to update in the branch table vs. having them globally. In the process of cleaning up the code and now onto the PUSH/POP instructions.

**Comment by lcampbe79** [comment]
(7854100) With the help from pair programming I was able to update the trace function to include how to print the PC, RM, Register # and Stack and complete the PUSH/POP functions.

**Review by gisturiz — APPROVED** [review]

**Pull request merged**
